### ISSUE TITLE
New Postman icon

### ISSUE THREAD

**Issue by smashism** [autopkg/killahquam-recipes#11]
Howdy, we noticed that 6.2.3 of Postman ships with a new icon. Here's a copy to update the png file for the recipe.

<img width="256" alt="install" src="https://user-images.githubusercontent.com/7853266/44114706-9c72dd08-9fd1-11e8-8d9d-6d9d651c75ad.png">

**Comment by killahquam** [comment]
Icon has been updated.

**Comment by smashism** [comment]
🎉
