### ISSUE TITLE
URL now pulls a .zip as opposed to the .dmg that the installer is expecting.

### ISSUE THREAD

**Issue by Deej-McDeej** [autopkg/killahquam-recipes#13]

**Comment by tcinbis** [comment]
I guess you refer to the Slack recipe... The according fix is already in PR #12

**Comment by adammartin253** [comment]
I have a ticket open with Slack to revert back to .dmg as there is a different bash script that does a similar process as this recipe that broke after the change. If they can't fix it I will have to go down the AutoPKG rabbit hole (haven't used it in my environment yet).

**Comment by WaveBirdDash** [comment]
https://slack.com/ssb/download-osx now appears to download a .dmg again, so presumably the change to .zip in the download recipe will need to be reverted.
