### ISSUE TITLE
Postman Recipe

### ISSUE THREAD

**Issue by patgmac** [autopkg/killahquam-recipes#16]
The parent recipe you're using for Postman appears to be no longer maintained since they're not accepting PR's at https://github.com/autopkg/bnpl-recipes/pull/10, which fixes the Postman download URL. 

Could you switch your Postman.jss recipe to use https://github.com/autopkg/dataJAR-recipes/blob/master/Postman/Postman.pkg.recipe?

**Comment by Bretterteig** [comment]
dataJAR has made a fork that is working.

Try using that as parent.

Regards.
