### ISSUE TITLE
Issue with BlueJeans jss recipe

### ISSUE THREAD

**Issue by tsinghzf** [autopkg/killahquam-recipes#19]
Specifically, one line of the code directs recipe to com.github.gregneagle.pkg.bluejeansapp for BlueJeans. This causes a breakage and unable to download and push jss recipe to Jamf

<key>ParentRecipe</key>
	<string>com.github.gregneagle.pkg.bluejeansapp</string>
	<key>Process</key>
	<array>

the issue is located on line 31. Please fix the plist as soon as possible.

Thank you

**Comment by killahquam** [comment]
Switched to a new parent recipe

**Comment by tsinghzf** [comment]
Thank you for the quick fix. It is working now

Have a great weekend
