### ISSUE TITLE
Slack being dumb

### ISSUE THREAD

**Issue by arubdesu** [autopkg/killahquam-recipes#4]
They seem to have abandoned the sparkle feed, and provided no upgrade path except hitting the publicly available download URL (that you were originally using) manually, or using the MAS version. Please revert to this commit: https://github.com/autopkg/killahquam-recipes/blob/caabf3d8d6ecb4d50b6764ab5c8d47f98d48b39b/Slack/Slack.download.recipe

**Comment by killahquam** [comment]
Should be good now!

**Comment by timsutton** [comment]
Also, Slack's beta page mentioned that their 2.2/2.3 betas require 10.9. Their `LSMinimumSystemVersion` is 10.8. Which is it?

**Comment by timsutton** [comment]
And actually, all previous 2.0 versions had `LSMinimumSystemVersion` of 10.9.

**Comment by timsutton** [comment]
Just left /feedback in the app, it's acknowledged and apparently being corrected now.
